spring:
  application:
    name: auth-service

  data:
    mongodb:
      database: auth-mongo-db
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            key:
              serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        medicorumUserChanged:
          destination: medicorum.user.changed
          contentType: application/json

server:
  port: 9045

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka


security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400000
    secret: JwtSecretKey

  service:
    username: serviceusername
    password: servicepassword

  oauth2:
    resource:
      filter-order: 3