spring:
  application:
    name: discussion-service

  data:
    mongodb:
      database: discussion-mongo-db
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            key:
              serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 9006

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka